In [29]:
import matplotlib as matplot
import seaborn
import bokeh
import keras
import numpy
import scipy
import pandas as pd
# import block

In [3]:
ncs1 = pd.read_csv("ICPSR_06693-V6/ICPSR_06693/DS0001/06693-0001-Data.tsv", sep = "\t")
# ncs1 includes all of the symptom data from the NCS Data

In [4]:
ncs1 = pd.DataFrame(ncs1)
#turn into pandas DF

In [5]:
ncs1

,CASEID,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V7437,V7438,V7439,V7440,V7441,V7442,P1FWT,P2WTV3,TOBACWT,P2TOBWT
0,10001,60080192,1,8128,9,28,90,9,28,90,...,9,9,9,9,99,9,0.5135,,0.5883,
1,10002,16030048,1,3941,10,1,90,10,1,90,...,9,9,9,9,99,9,1.8968,,2.1730,
2,10003,74070592,1,7813,10,5,90,10,5,90,...,9,9,9,9,99,9,0.4100,,0.4697,
3,10004,74030720,1,7813,10,10,90,10,10,90,...,9,9,9,9,99,9,0.3093,,0.3543,
4,10005,4180080,1,9018,10,10,90,10,10,90,...,9,9,9,9,99,9,0.7790,,0.8924,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8093,25952,44110688,6,8331,11,8,91,11,8,91,...,0,0,0,0,0,0,3.1569,,3.6165,
8094,25953,1130821,5,4260,8,21,91,11,13,91,...,5,5,0,1,99,9,0.1200,.2128,0.1375,.3332
8095,25954,18070448,4,5319,7,7,91,7,7,91,...,0,0,0,0,0,0,0.8161,.6435,0.9349,1.0076
8096,25955,1400261,6,8224,11,22,91,11,22,91,...,5,5,0,2,0,0,0.5060,,0.5797,
8097,25956,1471591,4,8224,8,25,91,10,11,91,...,0,0,0,0,0,0,0.9369,,1.0733,

In [26]:
ncs_sections = pd.DataFrame(data = {'Label': [], 'Subject': [], 'Part': [], 'Start': [], 'End': []})
ncs_sections

Empty DataFrame
Columns: [Label, Subject, Part, Start, End]
Index: []

In [27]:
ncs_a = ncs1.iloc[:, ncs1.columns.get_loc('V101'):ncs1.columns.get_loc('V250')]
ncs_a.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group A From DS001
ncs_sections.loc[len(ncs_sections)] = ['a', 'ACTIVITIES OF DAILY LIFE', 1, ncs1.columns.get_loc('V101'), ncs1.columns.get_loc('V250')]
# Adding description of section to ncs_sections

In [28]:
ncs_b = ncs1.iloc[:, ncs1.columns.get_loc('V301'):ncs1.columns.get_loc('V948')]
ncs_b.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group B From DS001
ncs_sections.loc[len(ncs_sections)] = ['b', 'LIFETIME MOODS AND HEALTH BEHAVIORS', 1, ncs1.columns.get_loc('V301'), ncs1.columns.get_loc('V948')]
ncs_sections
# Adding description of section to ncs_sections

  Label                              Subject  Part  Start    End
0     a             ACTIVITIES OF DAILY LIFE   1.0   15.0   78.0
1     b  LIFETIME MOODS AND HEALTH BEHAVIORS   1.0   79.0  361.0

In [8]:
ncs_c = ncs1.iloc[:, ncs1.columns.get_loc('V1001'):ncs1.columns.get_loc('V1016')]
ncs_c.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group C From DS001
ncs_sections.loc[len(ncs_sections)] = ['c', 'ONGOING SADNESS', 1]
# Adding description of section to ncs_sections

In [9]:
ncs_d = ncs1.iloc[:, ncs1.columns.get_loc('V1101'):ncs1.columns.get_loc('V1559')]
ncs_d.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group D From DS001
ncs_sections.loc[len(ncs_sections)] = ['d', 'SADNESS', 1]
# Adding description of section to ncs_sections

In [10]:
ncs_e = ncs1.iloc[:, ncs1.columns.get_loc('V1601'):ncs1.columns.get_loc('V1757')]
ncs_e.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group E From DS001
ncs_sections.loc[len(ncs_sections)] = ['e', 'MANIA', 1]
# Adding description of section to ncs_sections

In [11]:
ncs_f = ncs1.iloc[:, ncs1.columns.get_loc('V1801'):ncs1.columns.get_loc('V1816')]
ncs_f.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group F From DS001
ncs_sections.loc[len(ncs_sections)] = ['f', 'ALCOHOL', 1]
# Adding description of section to ncs_sections

In [12]:
ncs_g = ncs1.iloc[:, ncs1.columns.get_loc('V1817'):ncs1.columns.get_loc('V3757')]
ncs_g.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group G From DS001
ncs_sections.loc[len(ncs_sections)] = ['g', 'MEDICATION & DRUGS', 1]
# Adding description of section to ncs_sections

In [13]:
ncs_h = ncs1.iloc[:, ncs1.columns.get_loc('V3801'):ncs1.columns.get_loc('V3817')]
ncs_h.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group H From DS001
ncs_sections.loc[len(ncs_sections)] = ['h', 'PROBLEM BEHAVIORS', 1]
# Adding description of section to ncs_sections

In [14]:
ncs_j = ncs1.iloc[:, ncs1.columns.get_loc('V3901'):ncs1.columns.get_loc('V3936')]
ncs_j.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group J From DS001
ncs_sections.loc[len(ncs_sections)] = ['j', 'DEMOGRAPHICS', 1]
# Adding description of section to ncs_sections

In [15]:
ncs_aa = ncs1.iloc[:, ncs1.columns.get_loc('V4000'):ncs1.columns.get_loc('V4053')]
ncs_aa.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group AA From DS001
ncs_sections.loc[len(ncs_sections)] = ['aa', 'INTERVIEWER\'s OBSERVATIONS', 1]
# Adding description of section to ncs_sections

In [16]:
ncs_p2 = ncs1.iloc[:, ncs1.columns.get_loc('P2WTV3'):ncs1.columns.get_loc('V4100')]
ncs_p2.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group p2 From DS001
ncs_sections.loc[len(ncs_sections)] = ['p2', 'SURVEY ADMINISTRATION', 2]
# Adding description of section to ncs_sections

In [17]:
ncs_k = ncs1.iloc[:, ncs1.columns.get_loc('V4101'):ncs1.columns.get_loc('V4341')]
ncs_k.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group K From DS001
ncs_sections.loc[len(ncs_sections)] = ['k', 'BELIEFS AND EXPERIENCES', 2]
# Adding description of section to ncs_sections

In [18]:
ncs_l = ncs1.iloc[:, ncs1.columns.get_loc('V4401'):ncs1.columns.get_loc('V4447')]
ncs_l.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group L From DS001
ncs_sections.loc[len(ncs_sections)] = ['l', 'PERSONALITY', 2]
# Adding description of section to ncs_sections

In [19]:
ncs_m = ncs1.iloc[:, ncs1.columns.get_loc('V4501'):ncs1.columns.get_loc('V4629')]
ncs_m.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group M From DS001
ncs_sections.loc[len(ncs_sections)] = ['m', 'MARRIAGE', 2]
# Adding description of section to ncs_sections

In [20]:
ncs_n = ncs1.iloc[:, ncs1.columns.get_loc('V4701'):ncs1.columns.get_loc('V4824')]
ncs_n.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group N From DS001
ncs_sections.loc[len(ncs_sections)] = ['n', 'EMPLOYMENT', 2]
# Adding description of section to ncs_sections

In [21]:
ncs_p = ncs1.iloc[:, ncs1.columns.get_loc('V4901'):ncs1.columns.get_loc('V4917')]
ncs_p.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group P From DS001
ncs_sections.loc[len(ncs_sections)] = ['p', 'HOME AND WORK', 2]
# Adding description of section to ncs_sections

In [22]:
ncs_q = ncs1.iloc[:, ncs1.columns.get_loc('V5001'):ncs1.columns.get_loc('V5059')]
ncs_q.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group Q From DS001
ncs_sections.loc[len(ncs_sections)] = ['q', 'CHILDREN', 2]
# Adding description of section to ncs_sections

In [23]:
ncs_r = ncs1.iloc[:, ncs1.columns.get_loc('V5101'):ncs1.columns.get_loc('V5134')]
ncs_r.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group R From DS001
ncs_sections.loc[len(ncs_sections)] = ['r', 'SELF-DESCRIPTION', 2]
# Adding description of section to ncs_sections

In [24]:
ncs_s = ncs1.iloc[:, ncs1.columns.get_loc('V5201'):ncs1.columns.get_loc('V5938')]
ncs_s.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group S From DS001
ncs_sections.loc[len(ncs_sections)] = ['s', 'HEALTH', 2]
# Adding description of section to ncs_sections

In [25]:
ncs_t = ncs1.iloc[:, ncs1.columns.get_loc('V6001'):ncs1.columns.get_loc('V6019')]
ncs_t.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group T From DS001
ncs_sections.loc[len(ncs_sections)] = ['t', 'FINANCES', 2]
# Adding description of section to ncs_sections

In [26]:
ncs_u = ncs1.iloc[:, ncs1.columns.get_loc('V6101'):ncs1.columns.get_loc('V6318')]
ncs_u.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group U From DS001
ncs_sections.loc[len(ncs_sections)] = ['u', 'LIFE EVENT HISTORY', 2]
# Adding description of section to ncs_sections

In [27]:
ncs_v = ncs1.iloc[:, ncs1.columns.get_loc('V6401'):ncs1.columns.get_loc('V6541')]
ncs_v.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group V From DS001
ncs_sections.loc[len(ncs_sections)] = ['v', 'RECENT LIFE EVENTS', 2]
# Adding description of section to ncs_sections

In [28]:
ncs_x = ncs1.iloc[:, ncs1.columns.get_loc('V6601'):ncs1.columns.get_loc('V7028')]
ncs_x.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group X From DS001
ncs_sections.loc[len(ncs_sections)] = ['x', 'FAMILY HISTORY', 2]
# Adding description of section to ncs_sections

In [29]:
ncs_y = ncs1.iloc[:, ncs1.columns.get_loc('V7101'):ncs1.columns.get_loc('V7110')]
ncs_y.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group Y From DS001
ncs_sections.loc[len(ncs_sections)] = ['y', 'RELIGION', 2]
# Adding description of section to ncs_sections

In [30]:
ncs_z = ncs1.iloc[:, ncs1.columns.get_loc('V7111'):ncs1.columns.get_loc('V7141')]
ncs_z.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group Z From DS001
ncs_sections.loc[len(ncs_sections)] = ['z', 'RACIAL AND ETHNIC BACKGROUND', 2]
# Adding description of section to ncs_sections

In [31]:
ncs_bb = ncs1.iloc[:, ncs1.columns.get_loc('V7200'):ncs1.columns.get_loc('V732')]
ncs_bb.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)  
# Subset of question group BB From DS001
ncs_sections.loc[len(ncs_sections)] = ['bb', 'INTERVIEWER\'S OBSERVATIONS', 2]
# Adding description of section to ncs_sections

In [32]:
ncs_tobw = ncs1.iloc[:, ncs1.columns.get_loc('TOBACWT'):ncs1.columns.get_loc('V7442')]
ncs_tobw.insert(0, 'CASEID', ncs1.loc[:,'CASEID'], True)
# Subset of question group A From DS001
ncs_sections.loc[len(ncs_sections)] = ['tobw', 'TOBACCO USE SUPPLEMENT FREQUENCIES', 2]
# Adding description of section to ncs_sections

In [33]:
ncs_sections

   Subject                                 Part Label
0        a             ACTIVITIES OF DAILY LIFE     1
1        b  LIFETIME MOODS AND HEALTH BEHAVIORS     1
2        c                      ONGOING SADNESS     1
3        d                              SADNESS     1
4        e                                MANIA     1
5        f                              ALCOHOL     1
6        g                   MEDICATION & DRUGS     1
7        h                    PROBLEM BEHAVIORS     1
8        j                         DEMOGRAPHICS     1
9       aa           INTERVIEWER's OBSERVATIONS     1
10      p2                SURVEY ADMINISTRATION     2
11       k              BELIEFS AND EXPERIENCES     2
12       l                          PERSONALITY     2
13       m                             MARRIAGE     2
14       n                           EMPLOYMENT     2
15       p                        HOME AND WORK     2
16       q                             CHILDREN     2
17       r                     SELF-DESCRIPTION     2
18       s                               HEALTH     2
19       t                             FINANCES     2
20       u                   LIFE EVENT HISTORY     2
21       v                   RECENT LIFE EVENTS     2
22       x                       FAMILY HISTORY     2
23       y                             RELIGION     2
24       z         RACIAL AND ETHNIC BACKGROUND     2
25      bb           INTERVIEWER'S OBSERVATIONS     2
26    tobw   TOBACCO USE SUPPLEMENT FREQUENCIES     2